name: NewsClip
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pip=22.0.4
  - pytorch=1.12.0
  - torchvision=0.12.0
  - pip:
      - scikit-image==0.19.3
      - transformers==4.27.4
      - pymongo==4.3.3
      - tensorflow==2.12.0
      - git+https://github.com/openai/CLIP.git