name: NewsClip
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - cython=0.29.33
  - ipykernel=5.5.6
  - matplotlib=3.7.1
  - numpy=1.22.4
  - pip=22.0.4
  - pillow=9.5.0
  - pytorch=2.0.0
  - pyyaml=6.0
  - torchvision=0.15.1
  - pip:
      - protobuf==3.20.3
      - scikit-image==0.19.3
      - python-dateutil==2.8.2 
      - pandas==1.4.4
      - h5py==3.8.0
      - transformers==4.27.4
      - tqdm==4.65.0
      - pymongo==4.3.3
      - tensorflow==2.12.0
      - git+https://github.com/openai/CLIP.git
